### PR TITLE
Feature/metadata field

### PR DESCRIPTION
**Pull request by danhanson**
Vehicles and commodities now have a metadata field that replaces the param and capacity fields. It holds an arbitrary json object

Vehicles now look like this:

```
{
   "id":1,
   "longitude":20,
   "latitude":30,
   "status":"Online",
   "metadata":{"capacity":10}
}
```

Commodities look like this

```
{
   "id":2,
   "startLongitude":3,
   "startLatitude":4,
   "endLongitude":5,
   "endLatitude":6,
   "status":"Waiting",
   "metadata":{
      "height":10,
      "width":20,
      "length":30,
      "weight":2,
      "name":"box"
   }
}
```

### CODE REVIEW

**Comment by robinsdm** [comment]
@danhanson So "param" was changed to "metadata"? It does seem like a better name for that field.

**Comment by aj-michael** [comment]
Hooray for deleting code!

**Comment by danhanson** [comment]
Yeah I changed it to metadata, this probably breaks things that reads the messages though

**Comment by aj-michael** [comment]
:shipit:

**Comment by robinsdm** [comment]
@danhanson can you update the websocket api, please.

**Comment by aj-michael** [comment]
Also Dan, please do a release if you haven't yet. David needs something to test against.

**Comment by danhanson** [comment]
Yeah it was released

**Comment by danhanson** [comment]
the documentation was updated on the websocket api

**Comment by aj-michael** [comment]
Thanks Dan :+1:

**Comment by robinsdm** [comment]
@danhanson Vehicles don't exist any more. They need to be changed to Transports.

**Comment by danhanson** [comment]
They are still called vehicles in the server, I guess I could change it though

**Comment by robinsdm** [comment]
Intellij has a very nice find and replace all feature.

**Pull request merged**
