### PR TITLE
updated cluster router to deal with commodity pickups

### PR DESCRIPTION
**Pull request by danhanson**
I updated cluster router to work with commodity pickups

### CODE REVIEW

**Comment by aj-michael** [comment]
Your code is too complicated, I can't easily read it. I will wait to pull this after we test it out live.

**Comment by aj-michael** [comment]
And for the tests to be fixed.

**Comment by aj-michael** [comment]
this doesn't even compile..

**Comment by aj-michael** [comment]
Does this work? Have you tested it?

**Comment by danhanson** [comment]
I got this one to route an in transit commodity

**Comment by danhanson** [comment]
I also fixed some weird problem where the objective function is null when it is put in the message

**Comment by aj-michael** [comment]
Awesome! :+1:

**Pull request merged**
