### PR TITLE
Feature/websocket

### PR DESCRIPTION
**Pull request by danhanson**
added websocket API support for vehicles

create vehicle:

```
{
  "create":{
    "model":"Vehicle",
    "value":{
      "latitude":11,
      "longitude:12,
      "capacity":5
    }
  }
}
```

update vehicle

```
{
   "update":{
    "model":"Vehicle",
    "id":10,
    "value":{
      "latitude":12,
      "longitude":13
    }
}
```

delete vehicle

```
{
    "delete":{
      "model":"Vehicle",
      "id":3
    }
}
```

read vehicle

```
{
    "read":{
      "model":"Vehicle",
      "id":5
    }
}
```

### CODE REVIEW

**Comment by aj-michael** [comment]
@danhanson Can you rebase this into 1 (maybe 2) commits? I'd like to look through it commit by commit, but I cannot do that at the moment because you added things that you later deleted.

**Comment by aj-michael** [comment]
@danhanson WebSocketController is incompatible with Java models because we cannot add implicit Reads/Writes.

**Comment by aj-michael** [comment]
All of the HTTP stuff now works with the Scala models. I have personally tested all of the sockets commands and I think they are good to go. Please merge @danhanson

**Comment by danhanson** [comment]
We should eventually write more tests

**Comment by aj-michael** [comment]
I agree, test coverage is unfortunately low

**Pull request merged**
