### PR TITLE
Authorization header

### PR DESCRIPTION
**Pull request by danhanson**
This changes the app id in all paths to /root and requires either setting the AppId cookie or Authorization header to the application id to complete a websocket request.

### CODE REVIEW

**Comment by danhanson** [comment]
the tests need to be updated, don't pull yet

**Comment by aj-michael** [comment]
Lol the commits are from "root"

**Comment by aj-michael** [comment]
Delete the swap files. Those should be gitignored.

**Comment by danhanson** [comment]
yeah I committed from the server

**Comment by danhanson** [comment]
tests are fixed

**Comment by aj-michael** [comment]
Niiiiiiiiiiiice :rocket:

**Pull request merged**
