### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by danhanson**
Added authentication support to pathfinder server, look here to update the sdks: https://github.com/CSSE497/pathfinder/wiki/authentication

When you make a socket request, a ConnectionId message is sent back which contains an id string for the connection.

Next you need to get a google open id connect token and the user's email to make a post request to https://auth.thepathfinder.xyz/connection with the following query parameters:

```
id_token
email
application_id
connection_id
```

Note that this will only work if the email is for an account who has signed up for the application, you can sign up for an application by visiting:
https://auth.thepathfinder.xyz/auth/google?return_token=true&application=an-app-id
this also displays your google id token

```
After that
```

### CODE REVIEW

**Comment by aj-michael** [comment]
How do I sign a user up for my application?

**Comment by aj-michael** [comment]
Why do I need to pass both email and id_token? In order to get the email I would have to look inside the id_token, but I'd rather just pass it along to the auth server and have it open it up. @danhanson

**Comment by danhanson** [comment]
It needs the email to verify the email from the google identity token

**Comment by danhanson** [comment]
The test errors are there because I committed a change that disabled evolutions, I can fix that

**Comment by aj-michael** [comment]
:rocket:

**Pull request merged**
