### PR TITLE
Publish transport movement while calculating route

### PR DESCRIPTION
**Pull request by danhanson**
This allows the server to send updated routed messages while new routes are being calculated, also allows the server to reroute after an error occurs when routing.

### CODE REVIEW

**Comment by danhanson** [comment]
I somehow removed more lines than I added, hopefully that improves code coverage

**Comment by aj-michael** [comment]
This doesn't work at all...

**Comment by aj-michael** [comment]
@danhanson Did you ever fix this?

**Comment by aj-michael** [comment]
@danhanson ?

**Comment by aj-michael** [comment]
@danhanson , this is now 2 months old. What are we doing with this?

**Pull request closed without merging**
