### PR TITLE
Release 0.2.4 and removed evolutions

### PR DESCRIPTION
**Pull request by aj-michael**
Dan please merge this when you confirm that your fixes are live.

### CODE REVIEW

**Comment by aj-michael** [comment]
Released: http://130.211.184.70:9000

**Comment by danhanson** [comment]
Alright we can remove the evolutions from the pathfinder-server repo so that it works, we can still use the pathfinder-db repo locally to make sure that the evolution files consistent, but it is not needed at all by the server as long as the tables are properly generated.

**Comment by danhanson** [comment]
Oops, accidently deleted the branch, I restored it since it is a release branch (we don't delete those, right?)

**Comment by aj-michael** [comment]
nah we can delete them, the whole point is that github generates a "tag" for the commit. If you go to the main page for the repo, there is a section marked "Releases" that keeps track of all the tagged commits.

**Comment by danhanson** [comment]
ok I'll delete it

**Comment by danhanson** [comment]
or you can

**Pull request merged**
