### PR TITLE
Feature/vehicle status

### PR DESCRIPTION
**Pull request by danhanson**
Vehicles now have a status field, it can be either 'Online' or 'Offline'. If the status is left out in a Create message, the status defaults to Offline.

### CODE REVIEW

**Comment by aj-michael** [comment]
Thanks for working on this Dan

**Comment by aj-michael** [comment]
Nice work increasing test coverage :+1:

**Comment by danhanson** [comment]
Wait how did I increase test coverage?

**Comment by danhanson** [comment]
I did not write any tests, but I guess the code I wrote is already tested by existing tests

**Comment by aj-michael** [comment]
LOL

**Pull request merged**
